config/routes.rb
Rails.application.routes.draw do
  resources :saida_produtos
  resources :produtos
  resources :entrada_produtos
  resources :estoques
  resources :destinos
  resources :fornecedores
  root to: 'visitors#index'

end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
end

app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
  before_action :set_estoque, only: [:show, :edit, :update, :destroy]

  # GET /estoques
  # GET /estoques.json
  def index
    @estoques = Estoque.all
  end

  # GET /estoques/1
  # GET /estoques/1.json
  def show
  end

  # GET /estoques/new
  def new
    @estoque = Estoque.new
  end

  # GET /estoques/1/edit
  def edit
  end

  # POST /estoques
  # POST /estoques.json
  def create
    @estoque = Estoque.new(estoque_params)

    respond_to do |format|
      if @estoque.save
        format.html { redirect_to @estoque, notice: 'Estoque was successfully created.' }
        format.json { render :show, status: :created, location: @estoque }
      else
        format.html { render :new }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estoques/1
  # PATCH/PUT /estoques/1.json
  def update
    respond_to do |format|
      if @estoque.update(estoque_params)
        format.html { redirect_to @estoque, notice: 'Estoque was successfully updated.' }
        format.json { render :show, status: :ok, location: @estoque }
      else
        format.html { render :edit }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estoques/1
  # DELETE /estoques/1.json
  def destroy
    @estoque.destroy
    respond_to do |format|
      format.html { redirect_to estoques_url, notice: 'Estoque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estoque
      @estoque = Estoque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estoque_params
      params.require(:estoque).permit(:nome)
    end
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/views/estoques/_form.html.haml
= simple_form_for(@estoque) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome, label:"Nome"

  .form-actions
    = f.submit "Salvar"

app/views/estoques/edit.html.haml
%h1 Editing estoque

= render 'form'

= link_to 'Show', @estoque
\|
= link_to 'Back', estoques_path

app/views/estoques/index.html.haml
%h1 Listing estoques

%table
  %thead
    %tr
      %th Nome
      %th
      %th
      %th

  %tbody
    - @estoques.each do |estoque|
      %tr
        %td= estoque.nome
        %td= link_to 'Show', estoque
        %td= link_to 'Edit', edit_estoque_path(estoque)
        %td= link_to 'Destroy', estoque, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Estoque', new_estoque_path

app/views/estoques/new.html.haml
%h1 New estoque

= render 'form'

= link_to 'Back', estoques_path

app/views/estoques/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @estoque.nome

= link_to 'Edit', edit_estoque_path(@estoque)
\|
= link_to 'Back', estoques_path