config/routes.rb
Rails.application.routes.draw do
  resources :saida_produtos
  resources :produtos
  resources :entrada_produtos
  resources :estoques
  resources :destinos
  resources :fornecedores
  root to: 'visitors#index'

end

app/models/entrada_produto.rb
class EntradaProduto < ActiveRecord::Base
  belongs_to :itemProduto
  belongs_to :fornecedor
end

app/controllers/entrada_produtos_controller.rb
class EntradaProdutosController < ApplicationController
  before_action :set_entrada_produto, only: [:show, :edit, :update, :destroy]

  # GET /entrada_produtos
  # GET /entrada_produtos.json
  def index
    @entrada_produtos = EntradaProduto.all
  end

  # GET /entrada_produtos/1
  # GET /entrada_produtos/1.json
  def show
  end

  # GET /entrada_produtos/new
  def new
    @entrada_produto = EntradaProduto.new
  end

  # GET /entrada_produtos/1/edit
  def edit
  end

  # POST /entrada_produtos
  # POST /entrada_produtos.json
  def create
    @entrada_produto = EntradaProduto.new(entrada_produto_params)

    respond_to do |format|
      if @entrada_produto.save
        format.html { redirect_to @entrada_produto, notice: 'Entrada produto was successfully created.' }
        format.json { render :show, status: :created, location: @entrada_produto }
      else
        format.html { render :new }
        format.json { render json: @entrada_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrada_produtos/1
  # PATCH/PUT /entrada_produtos/1.json
  def update
    respond_to do |format|
      if @entrada_produto.update(entrada_produto_params)
        format.html { redirect_to @entrada_produto, notice: 'Entrada produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrada_produto }
      else
        format.html { render :edit }
        format.json { render json: @entrada_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrada_produtos/1
  # DELETE /entrada_produtos/1.json
  def destroy
    @entrada_produto.destroy
    respond_to do |format|
      format.html { redirect_to entrada_produtos_url, notice: 'Entrada produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada_produto
      @entrada_produto = EntradaProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_produto_params
      params.require(:entrada_produto).permit(:data, :utilizador, :itemProduto_id, :fornecedor_id)
    end
end

app/helpers/entrada_produtos_helper.rb
module EntradaProdutosHelper
end

app/views/entrada_produtos/_form.html.haml
= simple_form_for(@entrada_produto) do |f|
  = f.error_notification

  .form-inputs
    = f.input :data, label:"Data Entrada"
    = f.input :utilizador, label:"Utilizador"
    = f.association :itemProduto, label: "Quantidade", label_method: :quantidade
    = f.association :fornecedor, label: "Nome Fornecedor", label_method: :nome

  .form-actions
    = f.submit "Salvar"

app/views/entrada_produtos/edit.html.haml
%h1 Editing entrada_produto

= render 'form'

= link_to 'Show', @entrada_produto
\|
= link_to 'Back', entrada_produtos_path

app/views/entrada_produtos/index.html.haml
%h1 Listing entrada_produtos

%table
  %thead
    %tr
      %th Data
      %th Utilizador
      %th Itemproduto
      %th Fornecedor
      %th
      %th
      %th

  %tbody
    - @entrada_produtos.each do |entrada_produto|
      %tr
        %td= entrada_produto.data
        %td= entrada_produto.utilizador
        %td= entrada_produto.itemProduto.quantidade
        %td= entrada_produto.fornecedor.nome
        %td= link_to 'Show', entrada_produto
        %td= link_to 'Edit', edit_entrada_produto_path(entrada_produto)
        %td= link_to 'Destroy', entrada_produto, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entrada produto', new_entrada_produto_path

app/views/entrada_produtos/new.html.haml
%h1 New entrada_produto

= render 'form'

= link_to 'Back', entrada_produtos_path

app/views/entrada_produtos/show.html.haml
%p#notice= notice

%p
  %b Data:
  = @entrada_produto.data
%p
  %b Utilizador:
  = @entrada_produto.utilizador
%p
  %b Itemproduto:
  = @entrada_produto.itemProduto.quantidade
%p
  %b Fornecedor:
  = @entrada_produto.fornecedor.nome

= link_to 'Edit', edit_entrada_produto_path(@entrada_produto)
\|
= link_to 'Back', entrada_produtos_path