config/routes.rb
Rails.application.routes.draw do
  resources :saida_produtos
  resources :produtos
  resources :entrada_produtos
  resources :estoques
  resources :destinos
  resources :fornecedores
  root to: 'visitors#index'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :estoque
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :unidade, :setor, :valor_referencia, :valor_venda, :saldo, :estoque_id)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.haml
= simple_form_for(@produto) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :unidade
    = f.input :setor
    = f.input :valor_referencia, label:"Valor Referencia"
    = f.input :valor_venda, label:"Valor Venda"
    = f.input :saldo
    = f.association :estoque, label: "Nome Estoque", label_method: :nome

  .form-actions
    = f.submit "Salvar"

app/views/produtos/edit.html.haml
%h1 Editing produto

= render 'form'

= link_to 'Show', @produto
\|
= link_to 'Back', produtos_path

app/views/produtos/index.html.haml
%h1 Listing produtos

%table
  %thead
    %tr
      %th Nome
      %th Unidade
      %th Setor
      %th Valor referencia
      %th Valor venda
      %th Saldo
      %th Estoque
      %th
      %th
      %th

  %tbody
    - @produtos.each do |produto|
      %tr
        %td= produto.nome
        %td= produto.unidade
        %td= produto.setor
        %td= produto.valor_referencia
        %td= produto.valor_venda
        %td= produto.saldo
        %td= produto.estoque.nome
        %td= link_to 'Show', produto
        %td= link_to 'Edit', edit_produto_path(produto)
        %td= link_to 'Destroy', produto, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Produto', new_produto_path

app/views/produtos/new.html.haml
%h1 New produto

= render 'form'

= link_to 'Back', produtos_path

app/views/produtos/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @produto.nome
%p
  %b Unidade:
  = @produto.unidade
%p
  %b Setor:
  = @produto.setor
%p
  %b Valor referencia:
  = @produto.valor_referencia
%p
  %b Valor venda:
  = @produto.valor_venda
%p
  %b Saldo:
  = @produto.saldo
%p
  %b Estoque:
  = @produto.estoque.nome

= link_to 'Edit', edit_produto_path(@produto)
\|
= link_to 'Back', produtos_path