config/routes.rb
Rails.application.routes.draw do
  resources :saida_produtos
  resources :produtos
  resources :entrada_produtos
  resources :estoques
  resources :destinos
  resources :fornecedores
  root to: 'visitors#index'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
  %li= link_to 'Home', root_path
  %li= link_to 'Cadastrar Fornecedores', fornecedores_path
  %li= link_to 'Cadastrar Destinos', destinos_path
  %li= link_to 'Cadastrar Estoques', estoques_path
  %li= link_to 'Entrada Produtos', entrada_produtos_path
  %li= link_to 'Cadastrar Produto', produtos_path
  %li= link_to 'Saida Produto', saida_produtos_path
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Projeto P3'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Projeto P3'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield